-- Drop the tables
DROP TABLE zipcodes;

-- Create tables
CREATE TABLE zipcodes (RecordNumber int, Country string, City string, Zipcode int)
PARTITIONED BY (state string)
CLUSTERED BY (Zipcode) INTO 3 BUCKETS
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ',';

-- Load Data
LOAD DATA LOCAL INPATH '/root/zipcodes.csv' INTO TABLE zipcodes;

-- Display data from PR
SELECT * FROM zipcodes where state='PR' AND zipcode=704;